[package]
name = "host"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow.workspace = true
nix.workspace = true
tokio.workspace = true
serde.workspace = true
serde_json.workspace = true
futures.workspace = true
aws-nitro-enclaves-nsm-api.workspace = true
vsock.workspace = true
common = { path = "../common" }